apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name | quote }}
      {{ if .Values.podPriorityClass.enabled }}
      priorityClassName: {{ .Values.podPriorityClass.name }}
      {{ end }}
      containers:
      - name: hcloud-node-health
        image: {{ .Values.registry.image | quote }}
        imagePullPolicy: {{ .Values.registry.imagePullPolicy | quote }}
        env:
        - name: HCLOUD_TOKEN
          valueFrom:
            secretKeyRef:
              name: hcloud
              key: token
        resources:
          requests:
            cpu: 10m
            memory: 100Mi